# Generated by Django 5.1.2 on 2024-10-16 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_reservation_date_booking_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(verbose_name=datetime.time(2, 39)),
        ),
    ]
