# Generated by Django 5.1.2 on 2024-10-16 02:44

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(default=restaurant.models.Booking.default_reservation_time),
        ),
    ]
