# Generated by Django 5.1.2 on 2024-10-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_booking_reservation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item',
            new_name='menu_item_description',
        ),
    ]
