# Generated by Django 5.1.2 on 2024-10-16 03:53

import datetime
import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_menu_item_menu_menu_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.date.today, validators=[restaurant.models.Booking.validate_reservation_date]),
        ),
    ]
